import React,{useEffect,useState} from "react";
import {CalendarIcon,ReaderIcon,ReloadIcon} from "@radix-ui/react-icons";
type Day={date:string;label:string;absence:string;details?:string;start?:string;end?:string};
declare global {interface Window {webkit?:any; receivePlanning?:(data:any)=>void}}
export default function LiveCalendar(){
 const [data,setData]=useState<{days:Day[],syncedAt?:string}>(()=>{try{return JSON.parse(localStorage.getItem("planning")||'{"days":[]}')}catch{return {days:[]}}});
 const [month,setMonth]=useState(()=>new Date().toISOString().slice(0,7));
 const [selected,setSelected]=useState<Day|null>(null);
 const [tab,setTab]=useState("Calendrier");
 const [status,setStatus]=useState("");
 useEffect(()=>{window.receivePlanning=(value)=>{if(!Array.isArray(value.days))return; const incoming=value.days as Day[];const replaced=new Set(incoming.map(d=>d.date));setData(old=>{const next={days:[...old.days.filter(d=>!replaced.has(d.date)),...incoming],syncedAt:new Date().toISOString()};localStorage.setItem("planning",JSON.stringify(next));return next});if(incoming.length)setMonth(incoming[Math.floor(incoming.length/2)].date.slice(0,7));setStatus(value.warning||"Planning importé")}; return()=>{delete window.receivePlanning}},[]);
 function sync(){if(window.webkit?.messageHandlers?.selfservice){window.webkit.messageHandlers.selfservice.postMessage("open")}else setStatus("La connexion Selfservice est disponible dans l’application iPhone.")}
 const first=new Date(month+"-01T12:00:00"); const offset=(first.getDay()+6)%7;const count=new Date(first.getFullYear(),first.getMonth()+1,0).getDate();const total=Math.ceil((offset+count)/7)*7;
 const cells=Array.from({length:total},(_,i)=>{const d=i-offset+1;return {n:d,key:month+"-"+String(d).padStart(2,"0"),valid:d>0&&d<=count}});
 function move(delta:number){const date=new Date(first.getFullYear(),first.getMonth()+delta,1,12);setMonth(date.getFullYear()+"-"+String(date.getMonth()+1).padStart(2,"0"))}
 return <><div className="app-screen native-scroll"><main className="calendar-screen"><header className="top-area"><button onClick={()=>move(-1)} aria-label="Mois précédent">Préc.</button><h1 style={{fontSize:28,textTransform:"capitalize"}}>{first.toLocaleDateString("fr-FR",{month:"long"})}</h1><button onClick={()=>move(1)} aria-label="Mois suivant">Suiv.</button></header><section className="sync-card"><div><div className="sync-title">RATP Shift</div><p>{data.syncedAt?"Importé le "+new Date(data.syncedAt).toLocaleDateString("fr-FR"):"Connecter mon planning"}</p></div><button onClick={sync}><ReloadIcon/> Actualiser</button></section>{status&&<p role="status" style={{padding:10,fontSize:13}}>{status}</p>}
 {tab==="Tableau"?<section className="detail-card"><h2>Tableau</h2><p>Les fiches de travail seront disponibles ici prochainement.</p></section>:<><section className="calendar-card"><div className="weekday-row">{["L","M","M","J","V","S","D"].map((d,i)=><span key={i}>{d}</span>)}</div>{Array.from({length:total/7},(_,w)=><div className="calendar-week" key={w}>{cells.slice(w*7,w*7+7).map((c,i)=>{const day=data.days.find(d=>d.date===c.key);return <button className="calendar-day" key={i} onClick={()=>c.valid&&setSelected(day||{date:c.key,label:"Non importé",absence:""})}><span className="day-number">{c.valid?c.n:""}</span>{day&&<span className="shift-stack"><span className={"shift "+(day.label==="R"?"shift-green":"shift-cyan")}>{day.label==="R"?"Repos":day.label.replace("GERV_","")}</span>{day.absence&&<span className="shift shift-pink">{day.absence}</span>}</span>}</button>})}</div>)}</section>{!data.days.length&&<p style={{padding:16}}>Aucun planning importé. Connecte-toi à Selfservice avec « Actualiser ».</p>}</>}
 <div className="bottom-clearance"/></main></div><nav className="bottom-nav" style={{gridTemplateColumns:"1fr 1fr"}}><button className={tab==="Calendrier"?"active":""} onClick={()=>setTab("Calendrier")}><CalendarIcon/>Calendrier</button><button className={tab==="Tableau"?"active":""} onClick={()=>setTab("Tableau")}><ReaderIcon/>Tableau</button></nav>
 {selected&&<div className="sheet-overlay" onClick={()=>setSelected(null)}><section className="bottom-sheet" onClick={e=>e.stopPropagation()}><button className="close-sheet" onClick={()=>setSelected(null)}>Fermer</button><h2>{selected.date}</h2><h3>{selected.label==="R"?"Repos":selected.label}</h3>{selected.start&&<p>{selected.start} — {selected.end||"Fin non disponible"}</p>}<p style={{whiteSpace:"pre-line"}}>{selected.details||"Détails non importés."}</p></section></div>}</>
}

